### ISSUE TITLE
Warn when something derives `Debug`

### ISSUE THREAD

**Issue by SiebenCorgie** [EmbarkStudios/rust-gpu#751] opened 2021-09-12 18:23 UTC
When a struct derives the `Debug` trait, compilation fails with a strange error. For instance this struct

```
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct GpuCamera2d {
    pub location: [f32; 2],
    pub extent: [f32; 2],
    pub pad1: [f32; 3],
    pub rotation: f32,
}
```

Fails with the error:
```
     Compiling shared v0.1.0 (/../../shared)
  error: Cannot cast between pointer types
     --> /.../.../nightly-2021-08-27-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/array/mod.rs:219:9
      |
  219 |         Index::index(self as &[T], index)
      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: from: *[f32; 2]
      = note: to: *[f32]

  error: Cannot cast between pointer types
     --> /.../.../nightly-2021-08-27-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/array/mod.rs:219:9
      |
  219 |         Index::index(self as &[T], index)
      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: from: *[f32; 3]
      = note: to: *[f32]

  error: could not compile `shared` due to 2 previous errors
```

While the error is probably expected, I still searched for a while until I found the error. It would probably be nice to have an error like "Debug not supported".

**Comment by khyperia** [comment] 2021-09-13 07:40
Unfortunately, this is a really difficult problem to solve (... as is everything else that we haven't fixed yet :stuck_out_tongue:). The issue is that rust-gpu never sees anything like `#[derive(Debug)]`, but instead a heap of rust code that looks exactly like the user wrote it, with no way to tell from what macro it was generated from, or even if it's generated at all. All it sees is some super wacky code that definitely won't work on the GPU, and so the only thing it can do is error on the bad code. Because of this, unfortunately, this issue will likely not be fixed any time soon.

This issue is mentioned in #744.

**Comment by XAMPPRocky** [comment] 2021-09-13 08:33
You could warn on any `std::fmt` usage, since that's what the `Debug` code generates and I don't think anything else in the module will work currently anyway.

**Comment by khyperia** [comment] 2021-09-13 08:35
Unfortunately it's not that simple. We need to consider all sorts of edge cases - for example, saying "you can't use `#[derive(Debug)]`" when directly referencing something in `std::fmt` is incorrect, confusing, and misleading.

**Comment by XAMPPRocky** [comment] 2021-09-13 08:53
> We need to consider all sorts of edge cases - for example, saying "you can't use #[derive(Debug)]" when directly referencing something in std::fmt is incorrect, confusing, and misleading.

Right, that's how you phrase the warning, if the detection algorithm is coarse, so is the error message. FWIW I think something like the following would be enough, but you could be smarter about the message with a blocklist of all the `std::fmt` items to say which specific item is being used.

> warning: Usage of `std::fmt`. This module will not compile on GPU platforms, remove or add `#[cfg(not(target_arch="spirv")]` to any `std::fmt` item, such as `Debug`, `Display`, `format!`, or `write!`.

**Comment by oisyn** [comment] 2022-11-16 15:48
Closing this as a won't fix for now. I'll keep it in #744 as a reference.

**Closed by oisyn** 2022-11-16 15:48 UTC
Labels: t: enhancement, s: wontfix
