### ISSUE TITLE
output filename collision between two builds of the same rustc_codegen_spirv crate

### ISSUE THREAD

**Issue by joshtriplett** [EmbarkStudios/rust-gpu#409] opened 2021-02-09 00:06 UTC
Building rust-gpu triggers https://github.com/rust-lang/cargo/issues/6313 in Cargo:

```text
warning: output filename collision.
The lib target `rustc_codegen_spirv` in package `rustc_codegen_spirv v0.2.0 (/home/josh/src/rust-gpu/crates/rustc_codegen_spirv)` has the same output filename as the lib target `rustc_codegen_spirv` in package `rustc_codegen_spirv v0.2.0 (/home/josh/src/rust-gpu/crates/rustc_codegen_spirv)`.
Colliding filename is: /home/josh/src/rust-gpu/target/release/deps/librustc_codegen_spirv.so
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The lib target `rustc_codegen_spirv` in package `rustc_codegen_spirv v0.2.0 (/home/josh/src/rust-gpu/crates/rustc_codegen_spirv)` has the same output filename as the lib target `rustc_codegen_spirv` in package `rustc_codegen_spirv v0.2.0 (/home/josh/src/rust-gpu/crates/rustc_codegen_spirv)`.
Colliding filename is: /home/josh/src/rust-gpu/target/release/librustc_codegen_spirv.so
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
```

This may potentially be an issue in Cargo, at least in part; the linked issue mentions several ways this can happen. However, it seemed worth reporting here for tracking.

This seems consistently repeatable for me, just by running `cargo build --release` in the root of the rust-gpu repository checkout.

**Comment by joshtriplett** [comment] 2021-02-09 00:34
It looks like this happens when building multiple crates at once. Building just the wgpu runner, or just the ash runner, seems to work. Building both at once (`cargo build --release -p example-runner-ash -p example-runner-wgpu`, or just `cargo build --release` to build everything) hits this issue.

I also can't reproduce this on a slower build system with less parallelism, but I can reliably reproduce it on a 96-way build system.

**Comment by khyperia** [comment] 2021-02-09 08:20
Ah, we discovered a similar (or the same?) issue in https://github.com/EmbarkStudios/rust-gpu/issues/72 and reported it here https://github.com/rust-lang/cargo/issues/8794 . I'll keep this open in case it's actually a different issue, and thanks for the context about issue 6313, I hadn't seen that!

(I believe that #72 is caused by building both debug and release versions of a crate at the same time (due to `[build-dependencies]` downgrading to debug), but that might be incorrect, as I don't have a good understanding of what's happening)

**Comment by khyperia** [comment] 2021-12-08 10:00
I haven't seen this in a long while, and `cargo build --release` no longer repros for me, so, _something_ changed, either in rust-gpu or cargo. No idea what, but, I guess closing as it no longer happens!

**Closed by khyperia** 2021-12-08 10:00 UTC
Labels: t: bug
