### ISSUE TITLE
spirv-builder defaults don't match documentation. 

### ISSUE THREAD

**Issue by charles-r-earp** [EmbarkStudios/rust-gpu#297] opened 2020-12-02 05:20 UTC
Both spirv_version and memory_model default to None, even though the docs indicate 1.3 and Vulkan. With neither specified, the "-C --target-feature={}" flag isn't provided to rustc, which then inherits the target features of the host. On platforms supporting say sse, this will break glam because it assumes that sse implies x86 and anyway, it leads to a ton of really unhelpful errors about duplicate trait implementations.

Here's a snippet of spirv-builder/src/lib.rs:

    pub struct SpirvBuilder {
        path_to_crate: PathBuf,
        print_metadata: bool,
        spirv_version: Option<(u8, u8)>,
        memory_model: Option<MemoryModel>,
    }
    impl SpirvBuilder {
        pub fn new(path_to_crate: impl AsRef<Path>) -> Self {
            Self {
                path_to_crate: path_to_crate.as_ref().to_owned(),
                print_metadata: true,
                spirv_version: None,
                memory_model: None,
            }
        }

        /// Whether to print build.rs cargo metadata (e.g. cargo:rustc-env=var=val). Defaults to true.
        pub fn print_metadata(mut self, v: bool) -> Self {
            self.print_metadata = v;
            self
        }

        /// Sets the SPIR-V binary version to use. Defaults to v1.3.
        pub fn spirv_version(mut self, major: u8, minor: u8) -> Self {
            self.spirv_version = Some((major, minor));
            self
        }

        /// Sets the SPIR-V memory model. Defaults to Vulkan.
        pub fn memory_model(mut self, memory_model: MemoryModel) -> Self {
            self.memory_model = Some(memory_model);
            self
        }

        /// Builds the module. Returns the path to the built spir-v file. If print_metadata is true,
        /// you usually don't have to inspect the path, as the environment variable will already be
        /// set.
        pub fn build(self) -> Result<PathBuf, SpirvBuilderError> {
            let spirv_module = invoke_rustc(&self)?;
            let env_var = spirv_module.file_name().unwrap().to_str().unwrap();
            if self.print_metadata {
                println!("cargo:rustc-env={}={}", env_var, spirv_module.display());
            }
            Ok(spirv_module)
        }
    }

To reproduce, go to any of the runners and comment out `.spirv_version(1, 0)`. 

Idk, is this intended behavior? Potentially spirv-builder should error if no version is specified, or it should clear the inherited features. At the very least the docs should be more accurate.

**Comment by khyperia** [comment] 2020-12-02 08:35
Yeah, this is known, and is a duplicate of https://github.com/EmbarkStudios/rust-gpu/issues/294, and will be fixed soon. Thanks for the report!

**Closed by khyperia** 2020-12-02 08:35 UTC
Labels: t: bug
